version: '3'
services:
  proxy: 
    image: openresty/openresty:alpine-apk 
    container_name: guardbear
    volumes:
      - ./proxy_default.conf:/etc/nginx/conf.d/default.conf
      - ./cookie.lua:/lua-resty-cookie/lib/resty/cookie.lua
    ports:
      - 8080:80
      
  webserver:
    image: openresty/openresty:alpine-apk 
    container_name: 3rdparty_webserver
    volumes:
      - ./webserver_default.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
